#! /bin/bash
if [ ! -n "$1" ];then
    echo 'not input file'
    exit
fi
javac "$1.java"
filename=$1
head=${filename:0:1}
head="$(echo $head | tr '[:lower:]' '[:upper:]')"
tail=${filename:1}
filename=$head$tail
java $filename